"""An excerpt of the end-to-end suite: the deduplication, re-import, refused-batch and re-export
tests with every fixture and helper they use; the first-import, refused-statement, fixed-width
layout and rewritten-description tests are left out.

From PDF to export batch, on the synthetic statement: the guarantees the UI does not loosen.

These tests used to run against a client's statements and chart of accounts, and they left the
public suite along with them. They come back here on top of `synthetic_statement`: the same PDF that
`tests/test_synthetic_statement.py` proves closes at 0.00, now coming in through the workbench
import, getting classified, and turning into a batch file.

What this excerpt proves, in the order the accountant goes through it:

- re-importing does not duplicate: neither the same file, nor the same statement downloaded again,
  which only the SQLite `UNIQUE` constraint catches (see ADR 4);
- when the READING of the same file improves, the text is corrected in place, with no duplicate and
  no lost classification;
- the batch is refused WHOLE if a single entry has no account, and it does not go out twice without
  confirmation (see ADR 8).

Everything goes through the real APIs: `importing`, `repository`, the UI routes through
`TestClient`, and `exporting.generate`. The batch is generated by `exporting.generate` rather than
through its route, because the route writes to the output directory next to the default database,
outside `tmp_path`.

Chart-of-accounts names, category names and statement descriptions stay in Portuguese: they are the
data a Brazilian bank and accounting system print, and they flow into the batch as they are. Route
paths and form fields are those of the workbench's HTTP API.
"""

from __future__ import annotations

from datetime import datetime

import pytest
from fastapi.testclient import TestClient

from workbench import app, exporting, importing
from workbench import repository as repo
from workbench.schema import open_db
from export.record import read_file as read_export_record
from synthetic_statement import write_pdf, june_statement

PERIOD = "2026-06"

# The fictitious chart of accounts of METALURGICA HORIZONTE, with only what the June statement uses.
# The line without a code is a SUMMARY account: it exists to add up the others and takes no
# entries, so the chart leaves it out.
CHART_OF_ACCOUNTS = [
    ("1", "", "ATIVO"),
    ("1.1.1.02.001", "103-5", "SICOOB COOPCENTRAL C/C 12345-6"),
    ("1.1.2.01.001", "112-7", "CLIENTES"),
    ("2.1.1.01.001", "611-4", "FORNECEDORES"),
    ("2.1.3.01.004", "240-8", "PRO-LABORE A PAGAR"),
    ("4.2.1.03.002", "427-3", "TARIFAS BANCARIAS"),
]
BANK_LEDGER_CODE = "103-5"
# statement description -> the account the accountant classifies it under
CLASSIFICATION = {
    "PIX RECEB.OUTRA IF": "112-7",
    "DÉB.TIT.COMPE EFETIVADO": "611-4",
    "TARIFA COBRANÇA": "427-3",
    "PIX EMIT.OUTRA IF": "240-8",
    "LIBERAÇÃO DEP.BLOQUEADO": "112-7",
    "CRÉD.LIQ.COBRANÇA": "112-7",
}


@pytest.fixture(autouse=True)
def no_ocr(monkeypatch):
    """The synthetic PDF has a text layer. See the same fixture in
    `tests/test_synthetic_statement.py`: with tesseract on the machine, a refusal would go
    through the enlarged re-read, and the test would depend on the recognizer."""
    from statement import ocr

    monkeypatch.setattr(ocr, "available", lambda: False)


@pytest.fixture
def cx(tmp_path):
    return open_db(tmp_path / "end_to_end.db")


@pytest.fixture
def company(cx):
    return repo.create_company(cx, "METALURGICA HORIZONTE LTDA", "11.111.111/0001-92")


def pdf(tmp_path, statement=None, lines=None, label="sicoob-sisbr-2026-06.pdf") -> bytes:
    return write_pdf(tmp_path / label, statement or june_statement(), lines).read_bytes()


def run_import(cx, company, content, label="sicoob-sisbr-2026-06.pdf"):
    return importing.import_file(cx, company, label, content)


def entries(cx, company):
    return repo.entries(cx, company, PERIOD)


# --------------------------------------------------------------- re-importing


def test_reimporting_the_same_file_creates_no_entry(cx, company, tmp_path):
    """The same file (same hash) again: zero new entries."""
    content = pdf(tmp_path)
    first_import = run_import(cx, company, content)
    second = run_import(cx, company, content)

    assert (first_import.new_entries, first_import.duplicates) == (7, 0)
    assert second.accepted
    assert (second.new_entries, second.duplicates, second.corrected) == (0, 7, 0)
    assert repo.summary(cx, company, PERIOD)["total"] == 7


def test_same_statement_downloaded_again_does_not_duplicate(cx, company, tmp_path):
    """The case that only the database's `UNIQUE` constraint catches.

    The client downloads the June statement twice. The transactions are the same, but the bank
    stamps the time of issue, so the BYTES differ, and the "same file" shortcut (a lookup by
    content hash) does not recognize the second one. It goes on as a new statement all the way to
    `INSERT OR IGNORE`, and it is the schema's `UNIQUE (bank_account_id, identity)` that refuses
    each of the seven entries.

    Both statements are recorded as accepted: that is the proof that the second one went through
    the write path, and not through the shortcut.
    """
    morning = pdf(tmp_path, label="june-morning.pdf")
    afternoon = pdf(
        tmp_path,
        june_statement(issued_at=datetime(2026, 7, 1, 17, 45)),
        label="june-afternoon.pdf",
    )
    assert morning != afternoon, "without different bytes the test would hit the hash shortcut"

    run_import(cx, company, morning, "june-morning.pdf")
    second = run_import(cx, company, afternoon, "june-afternoon.pdf")

    assert second.accepted
    assert (second.new_entries, second.duplicates) == (0, 7)
    assert repo.summary(cx, company, PERIOD)["total"] == 7
    assert [e["accepted"] for e in repo.statements(cx, company)] == [1, 1]


def test_reimport_with_corrected_text_neither_duplicates_nor_loses_classification(
    cx, company, tmp_path, monkeypatch
):
    """When the READING improves, the same file yields different text.

    The description is part of the dedup identity, so a corrected text looks like a new entry, and
    re-importing would duplicate it. The first import simulates the old reading, with a defect the
    column parser documents: the first word of the description got lost, and `PIX RECEB.OUTRA IF`
    became `RECEB.OUTRA IF`. The money is the same; the file closes under both readings.

    The accountant classifies everything and rewrites the description of one entry. Re-importing
    with the correct reading fixes the text IN PLACE: nothing new, nothing duplicated, and the
    category, the account and the accountant's own text all intact.

    And the identity follows the text: the same statement, downloaded again after the fix, still
    does not duplicate. Without that, the corrected `PIX` would look "new" to the `UNIQUE`
    constraint on the next import.
    """
    from statement import pipeline

    correct_reading = pipeline.extract_pages

    def old_reading(pathname):
        pages = correct_reading(pathname)
        pix_line_tops = {p.top for page in pages for p in page if p.string == "RECEB.OUTRA"}
        return [
            [p for p in page if not (p.string == "PIX" and p.top in pix_line_tops)]
            for page in pages
        ]

    content = pdf(tmp_path)
    with monkeypatch.context() as before_fix:
        before_fix.setattr(pipeline, "extract_pages", old_reading)
        first_import = run_import(cx, company, content)
    assert first_import.accepted and first_import.new_entries == 7
    (target,) = [l for l in entries(cx, company) if l["description"] == "RECEB.OUTRA IF"]

    customers = repo.create_category(cx, company, "CLIENTES", "112-7")
    for line in entries(cx, company):
        repo.classify(cx, line["id"], customers, "112-7", None)
    repo.edit_description(cx, target["id"], "RECEBIMENTO DISTRIBUIDORA NORTE")

    second = run_import(cx, company, content)

    assert second.accepted
    assert (second.new_entries, second.duplicates, second.corrected) == (0, 7, 1)
    summary = repo.summary(cx, company, PERIOD)
    assert (summary["total"], summary["classified"]) == (7, 7)
    corrected_entry = repo.one_entry(cx, target["id"])
    assert corrected_entry["description"] == "PIX RECEB.OUTRA IF"
    assert corrected_entry["category_id"] == customers
    assert corrected_entry["ledger_account"] == "112-7"
    assert corrected_entry["edited_description"] == "RECEBIMENTO DISTRIBUIDORA NORTE"

    downloaded_again = pdf(
        tmp_path, june_statement(issued_at=datetime(2026, 7, 2, 9, 0)), label="again.pdf"
    )
    third = run_import(cx, company, downloaded_again, "again.pdf")
    assert (third.new_entries, third.duplicates) == (0, 7)
    assert repo.summary(cx, company, PERIOD)["total"] == 7


# ---------------------------------------------------------------------- batch


def upload_chart_of_accounts(client, company, tmp_path):
    """The chart of accounts comes in the way the accountant uploads it: an XLSX exported from the
    accounting system."""
    import openpyxl

    workbook = openpyxl.Workbook()
    workbook.active.append(["Classificação", "Código", "Descrição"])
    for line in CHART_OF_ACCOUNTS:
        workbook.active.append(list(line))
    pathname = tmp_path / "chart-of-accounts-metalurgica.xlsx"
    workbook.save(pathname)
    with open(pathname, "rb") as file:
        response = client.post(
            f"/api/companies/{company}/chart-of-accounts",
            files={"file": (pathname.name, file, "application/octet-stream")},
        )
    assert response.json() == {"accounts": 5}, response.text


def prepare(cx, company, tmp_path, leave_out=()):
    """Imports, links the bank account to the chart of accounts, and classifies through the UI.

    `leave_out` holds descriptions that stay unclassified.
    """
    client = TestClient(app.create_app(cx))
    upload_chart_of_accounts(client, company, tmp_path)
    assert run_import(cx, company, pdf(tmp_path)).accepted

    (account,) = repo.bank_accounts(cx, company)
    client.post(f"/api/bank-accounts/{account['id']}", data={"code": BANK_LEDGER_CODE})
    categories = {
        code: client.post(
            f"/api/companies/{company}/categories/from-chart", data={"code": code}
        ).json()["id"]
        for code in set(CLASSIFICATION.values())
    }
    for line in entries(cx, company):
        if line["description"] in leave_out:
            continue
        code = CLASSIFICATION[line["description"]]
        response = client.post(
            f"/api/entries/{line['id']}",
            data={"category_id": categories[code], "ledger_account": code},
        )
        assert response.json()["ok"], response.text
    return client


@pytest.mark.parametrize("scenario", ["no_category", "category_without_account"])
def test_one_entry_without_account_refuses_the_whole_batch(cx, company, tmp_path, scenario):
    """A partial batch in the accounting system is worse than no batch at all.

    Six entries are ready and the bank fee has no account: either it was forgotten, or it went into
    a category created without a code. Not a byte is written, nothing goes into the export record,
    and the diagnostic points to the line. Once the fee is classified, the same batch goes out: it
    was the fee, and only the fee, that held it back.
    """
    prepare(cx, company, tmp_path, leave_out={"TARIFA COBRANÇA"})
    (fee,) = [l for l in entries(cx, company) if l["description"] == "TARIFA COBRANÇA"]
    if scenario == "category_without_account":
        no_code_category = repo.create_category(cx, company, "DESPESAS A CLASSIFICAR")
        repo.classify(cx, fee["id"], no_code_category, None, None)
    destination, record = tmp_path / "batch.txt", tmp_path / "exported_batches.jsonl"

    assert exporting.readiness(cx, company, PERIOD)["ready"] is False
    result, content = exporting.generate(cx, company, PERIOD, destination, record=record)

    assert result.generated is False
    assert content is None
    assert not destination.exists(), "not even a partial file"
    assert not record.exists(), "a refusal leaves no export trace"
    (problem,) = result.diagnostics
    assert problem.code == "MISSING_ACCOUNT"
    assert "TARIFA COBRAN" in problem.message

    fees = repo.create_category(cx, company, "TARIFAS BANCARIAS", "427-3")
    repo.classify(cx, fee["id"], fees, "427-3", None)
    result, content = exporting.generate(cx, company, PERIOD, destination, record=record)
    assert result.generated and result.entry_count == 7


def test_reexporting_the_same_period_requires_confirmation(cx, company, tmp_path):
    """The batch is a one-way street.

    Importing the same file twice into the accounting system duplicates everything at the
    destination, and identical content does not change that. The second generation is refused
    without touching the file that already exists; once confirmed, it comes out byte for byte the
    same and is marked as a regeneration in the export record.
    """
    prepare(cx, company, tmp_path)
    destination, record = tmp_path / "batch.txt", tmp_path / "exported_batches.jsonl"

    first, content = exporting.generate(cx, company, PERIOD, destination, record=record)
    assert first.generated

    again, nothing = exporting.generate(cx, company, PERIOD, destination, record=record)
    assert again.generated is False and nothing is None
    (notice,) = again.diagnostics
    assert notice.code == "PERIOD_ALREADY_EXPORTED"
    assert notice.details["content_changed"] == "False"
    assert destination.read_bytes() == content

    confirmed, regenerated = exporting.generate(
        cx, company, PERIOD, destination, confirm_regeneration=True, record=record
    )
    assert confirmed.generated and confirmed.regeneration
    assert regenerated == content, "same input, same bytes"
    assert [e.regeneration for e in read_export_record(record)] == [False, True]
